---

apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-configs
data:
  MYSQL_ROOT_PASSWORD: rootpassword
  DB_NAME: testdb
  DB_USER: testuser
  DB_PASSWORD: testpassword
  DB_HOST: db-service.default.svc.cluster.local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: tupakula/k8_web_image:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: myapp-configs
                key: MYSQL_ROOT_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: myapp-configs
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: myapp-configs
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: myapp-configs
                key: DB_PASSWORD
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: myapp-configs
                key: DB_HOST         

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30008
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:8.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:

          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: myapp-configs
                key:  MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: myapp-configs
                key:  DB_NAME
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: myapp-configs
                key: DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: myapp-configs
                key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30009

      
      
      
        

