---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: tupakula/k8_web_image:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: rootpassword
          - name: DB_NAME
            value: testdb
          - name: DB_USER
            value: testuser
          - name: DB_PASSWORD
            value: testpassword
          - name: DB_HOST
            value: "db-service.default.svc.cluster.local"         

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30008
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:8.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: rootpassword
          - name: MYSQL_DATABASE
            value: testdb
          - name: MYSQL_USER
            value: testuser
          - name: MYSQL_PASSWORD
            value: testpassword

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30009

      
      
      
        

